name: Run yt.sh Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make liveyt.sh executable
        run: chmod +x liveyt.sh
        
      - name: Run liveyt.sh script
        run: ./liveyt.sh
